remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: true
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: true
  24 hours: true

positions:
  - Product Manager
  - Product Growth

locations:
  - Europe
  - Germany
  - Italy
  - Netherlands
  - France

apply_once_at_company: true

distance: 100

company_blacklist:
  - Sprinque
  - Orderchamp
  - Gigstarter
  - Grassroots

title_blacklist:
  - word1
  - word2

location_blacklist:
  - Brazil

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: gemini
llm_model: 'gemini-1.5-flash'
llm_api_url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent'